module.exports = {
  general: {
    avatar: {
      name: "Avatar",
      description: "Fetches the profile avatar of any user.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["av"],
      usage: "avatar [user]",
      required: "none",
      commandName: "avatar"
    },
    botinfo: {
      name: "Bot Info",
      description: "Provides information about Logic Link.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["binfo"],
      usage: "botinfo",
      required: "none",
      commandName: "botinfo"
    },
    help: {
      name: "Help",
      description: "Provides a list of commands.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["cmd", "cmds", "commands"],
      usage: "help [command name]",
      required: "none",
      commandName: "help"
    },
    info: {
      name: "Info",
      description: "Provides info about your server, channels and roles.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["serverinfo", "channelinfo", "roleinfo"],
      usage: "info <item>",
      required: "none",
      commandName: "info"
    },
    invite: {
      name: "Bot Invite",
      description: "Provides the invite link that you can use to add Logic Link to your server.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["inv"],
      usage: "invite",
      required: "none",
      commandName: "invite"
    },
    membercount: {
      name: "Member Count",
      description: "Provides the number of members in your server.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["mcount", "mc"],
      usage: "membercount",
      required: "none",
      commandName: "membercount"
    },
    pastebin: {
      name: "Pastebin",
      description: "Creates a new paste from https://pastebin.com.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 10800,
      minArgs: 1,
      options: ["new"],
      aliases: ["paste"],
      usage: "pastebin <option>",
      required: "none",
      commandName: "pastebin"
    },
    ping: {
      name: "Ping",
      description: "Checks the bot's latency.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "ping",
      required: "none",
      commandName: "ping"
    },
    ticket: {
      name: "Ticket",
      description: "Allows you to create and manage tickets.",
      permissions: ["ALL"],
      options: ["help", "new", "panelinfo", "stats", "tag", "ticketinfo", "add", "claim", "close", "delete", "open", "remove", "rename", "panel", "settings", "tags", "view"],
      aliases: ["tickets", "tck", "t"],
      usage: "ticket [option] [option parameter]",
      required: "none",
      commandName: "ticket",
      option: {
        help: {
          name: "Help",
          description: "The ticket help command is used to provide helpful information about certain commands.",
          permissions: ["ALL"],
          aliases: [],
          usage: "help [command name]",
          required: "none",
          commandName: "help"
        },
        new: {
          name: "New",
          description: "The ticket new command is used to open a new ticket in the provided panel.",
          permissions: ["ALL"],
          aliases: ["new"],
          usage: "new <panel name>",
          required: "none",
          commandName: "new"
        },
        panelinfo: {
          name: "panel info",
          description: "The ticket panelinfo command is used to provide information about a certain panel.",
          permissions: ["ALL"],
          aliases: ["panelinfo"],
          usage: "panelinfo <panel name>",
          required: "none",
          commandName: "panelinfo"
        },
        stats: {
          name: "stats",
          description: "The ticket stats command is used to provide information about the server ticket system.",
          permissions: ["ALL"],
          aliases: [],
          usage: "stats",
          required: "none",
          commandName: "stats"
        },
        tag: {
          name: "tag",
          description: "The ticket tag command is used to reveal information that was previously stored by a server admin.",
          permissions: ["ALL"],
          aliases: ["tag"],
          usage: "tag [tag name]",
          required: "none",
          commandName: "tag"
        },
        ticketinfo: {
          name: "ticket info",
          description: "The ticket ticketinfo command is used to provide information about a certain ticket.",
          permissions: ["ALL"],
          aliases: ["ticketinfo"],
          usage: "ticketinfo <channel id>",
          required: "none",
          commandName: "ticketinfo"
        },
        add: {
          name: "add",
          description: "The ticket add command is used to add users or roles to a ticket.",
          permissions: "SUPPORT_TEAM",
          aliases: ["add"],
          usage: "add <user | role>",
          required: "support",
          commandName: "add"
        },
        claim: {
          name: "claim",
          description: "The ticket claim command is used to designate support team members to different tickets with a claiming system.",
          permissions: "SUPPORT_TEAM",
          aliases: ["claim"],
          usage: "claim [channel id]",
          required: "support",
          commandName: "claim"
        },
        close: {
          name: "close",
          description: "The ticket close command is used to remove access to a ticket from the user who opened it.",
          permissions: "SUPPORT_TEAM",
          aliases: ["close"],
          usage: "close [channel id]",
          required: "support",
          commandName: "close"
        },
        delete: {
          name: "delete",
          description: "The ticket delete command is used to delete a ticket.",
          permissions: "SUPPORT_TEAM",
          aliases: [],
          usage: "delete [channel id]",
          required: "support",
          commandName: "delete"
        },
        open: {
          name: "open",
          description: "The ticket open command is used to re-open previously closed tickets back to the user who opened it.",
          permissions: "SUPPORT_TEAM",
          aliases: ["open", "reopen"],
          usage: "help [command name]",
          required: "support",
          commandName: "open"
        },
        remove: {
          name: "remove",
          description: "The ticket remove command is used to remove users or roles from having access to a ticket.",
          permissions: "SUPPORT_TEAM",
          aliases: ["remove"],
          usage: "remove <users | roles>",
          required: "support",
          commandName: "remove"
        },
        rename: {
          name: "rename",
          description: "The ticket rename command is used to change the name of a ticket.",
          permissions: "SUPPORT_TEAM",
          aliases: [],
          usage: "rename <new name>",
          required: "support",
          commandName: "rename"
        },
        panel: {
          name: "panel",
          description: "The ticket panel command is used to list and configure panel settings.",
          permissions: ["ALL"],
          options: ["new", "modify", "delete"],
          aliases: ["panel", "panels"],
          usage: "panel <option>",
          required: "admin",
          commandName: "panel",
          option: {
            new: {
              name: "new",
              description: "The ticket panel new command is used to create a new ticket panel for your server.",
              permissions: ["ALL"],
              aliases: ["ticket panel n"],
              usage: "new",
              required: "admin",
              commandName: "new"
            },
            modify: {
              name: "modify",
              description: "The ticket panel modify command is used to edit the configurations of a panel.",
              permissions: ["ALL"],
              options: ["name", "category_opened", "category_closed", "ticket_name", "claiming", "claimed_ticket_name", "support_roles", "additional_roles", "panel_channel"],
              aliases: ["ticket panel m"],
              usage: "modify <panel id> <option> <option parameter>",
              required: "admin",
              commandName: "modify",
              option: {
                name: {
                  name: "name",
                  description: "The ticket panel modify name command is used to edit the name of a panel.",
                  permissions: ["ALL"],
                  aliases: [],
                  usage: "modify <panel id> name <new name>",
                  required: "admin",
                  commandName: "name"
                },
                category_opened: {
                  name: "category opened",
                  description: "The ticket panel modify category_opened command is used to edit the category where opened tickets will be moved to.",
                  permissions: ["ALL"],
                  aliases: ["ticket panel modify cat_opened", "ticket panel modify cat_open"],
                  usage: "modify <panel id> category_opened <category id>",
                  required: "admin",
                  commandName: "category_opened"
                },
                category_closed: {
                  name: "category closed",
                  description: "The ticket panel modify category_closed command is used to edit the category where closed tickets will be moved to.",
                  permissions: ["ALL"],
                  aliases: ["ticket panel modify cat_closed", "ticket panel modify cat_close"],
                  usage: "modify <panel id> category_closed <category id>",
                  required: "admin",
                  commandName: "category_closed"
                },
                ticket_name: {
                  name: "ticket name",
                  description: "The ticket panel modify ticket_name command is used to edit the name of newly opened tickets",
                  permissions: ["ALL"],
                  aliases: ["ticket panel modify t_name"],
                  usage: "modify <panel id> ticket_name <new name>",
                  required: "admin",
                  commandName: "ticket_name"
                },
                claiming: {
                  name: "claiming",
                  description: "The ticket panel modify claiming command is used to turn the claiming system on or off.",
                  permissions: ["ALL"],
                  aliases: ["ticket panel modify claim"],
                  usage: "modify <panel id> claim <on | off>",
                  required: "admin",
                  commandName: "claiming"
                },
                claimed_ticket_name: {
                  name: "claimed ticket name",
                  description: "The ticket panel modify claimed_ticket_name command is used to edit the name of claimed tickets.",
                  permissions: ["ALL"],
                  aliases: ["ticket panel modify claimed_name"],
                  usage: "modify <panel id> claimed_ticket_name <new name>",
                  required: "admin",
                  commandName: "claimed_ticket_name"
                },
                support_roles: {
                  name: "support roles",
                  description: "The ticket panel modify support_roles command is used to edit the roles that are allowed to view and type in all tickets.",
                  permissions: ["all"],
                  aliases: ["ticket panel modify support", "ticket panel modify s_roles", "ticket panel modify s_role"],
                  usage: "modify <panel id> support_roles <new roles>",
                  required: "admin",
                  commandName: "support_roles"
                },
                additional_roles: {
                  name: "additional roles",
                  description: "The ticket panel modify additional_roles command is used to edit the roles that are able to view all tickets",
                  permissions: ["all"],
                  aliases: ["ticket panel modify additional", "ticket panel modify a_roles", "ticket panel modify s_role"],
                  usage: "modify <panel id> additional_roles <new roles>",
                  required: "admin",
                  commandName: "additional_roles"
                },
                panel_channel: {
                  name: "panel channel",
                  description: "The ticket panel modify panel_channel command is used to edit the channel that the panel is sent to.",
                  permissions: ["all"],
                  aliases: ["ticket panel modify p_channel"],
                  usage: "modify <panel id> panel_channel <new channel>",
                  required: "admin",
                  commandName: "panel_channel"
                },
              }
            },
          }
        },
        settings: {
          name: "settings",
          description: "The ticket settings command is used to list and configure global ticket settings.",
          permissions: ["ALL"],
          aliases: [],
          usage: "settings [option name]",
          required: "admin",
          commandName: "settings"
        },
        tags: {
          name: "tags",
          description: "The ticket tags command is used to configure tags to be used by normal members.",
          permissions: ["ALL"],
          aliases: ["tags"],
          usage: "tags <new | modify | delete>",
          required: "admin",
          commandName: "tags"
        },
        view: {
          name: "view",
          description: "The ticket view command is used to show a list of all active tickets and information about them.",
          permissions: ["ALL"],
          aliases: [],
          usage: "view",
          required: "admin",
          commandName: "view"
        },
      }
    },
    uptime: {
      name: "Up-Time",
      description: "Shows how long the bot has last been online for.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: [],
      aliases: ["up-time"],
      usage: "uptime",
      required: "none",
      commandName: "uptime"
    },
    voice: {
      name: "Voice",
      description: "Performs various voice channel actions.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 2,
      minArgs: 1,
      options: ["connect", "disconnect", "play", "pause"],
      aliases: ["vc"],
      usage: "voice <option>",
      required: "none",
      commandName: "voice",
      option: {
        connect: {
          name: "Voice - Connect",
          description: "Connects Logic Link to a voice channel.",
          permissions: ["ALL"],
          clientPerms: [],
          cooldown: 2,
          minArgs: 2,
          options: [],
          aliases: [],
          usage: "voice connect",
          required: "none",
          commandName: "voice connect"
        },
        disconnect: {
          name: "Voice - Disconnect",
          description: "Disconnects Logic Link from a voice channel.",
          permissions: ["ALL"],
          clientPerms: [],
          cooldown: 2,
          minArgs: 2,
          options: [],
          aliases: [],
          usage: "voice disconnect",
          required: "none",
          commandName: "voice disconnect"
        },
        play: {
          name: "Voice - Play",
          description: "Play any song or podcast from YouTube in a voice channel.",
          permissions: ["ALL"],
          clientPerms: [],
          cooldown: 2,
          minArgs: 2,
          options: [],
          aliases: [],
          usage: "voice play <search query>",
          required: "none",
          commandName: "voice play"
        },
        pause: {
          name: "Voice - Pause",
          description: "Pauses the currently playing audio.",
          permissions: ["ALL"],
          clientPerms: [],
          cooldown: 2,
          minArgs: 2,
          options: [],
          aliases: [],
          usage: "voice pause",
          required: "none",
          commandName: "voice pause"
        }
      }
    },
    whois: {
      name: "Who Is",
      description: "Retrieves information about a user.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 3,
      minArgs: 0,
      options: [],
      aliases: ["who-is"],
      usage: "whois [user]",
      required: "none",
      commandName: "whois"
    }
  },
  ticket: {
    thelp: {
      name: "Ticket Help",
      description: "Provides information about ticket commands.",
      permissions: ["ALL"],
      clientPerms: [],
      cooldown: 2,
      minArgs: 0,
      options: [],
      aliases: ["tickethelp"],
      usage: "thelp [command]",
      required: "ticket",
      commandName: "thelp"
    },
    panels: {
      name: "Ticket Panels",
      description: "Allows users to view or modify ticket panels.",
      permissions: ["ADMINISTRATOR"],
      clientPerms: [],
      cooldown: 3,
      minArgs: 0,
      options: [],
      aliases: ["panel", "tpanels"],
      usage: "panels [new | modify | delete]",
      required: "ticket",
      commandName: "panels",
      option: {
        new: {
          name: "Ticket Panels - New",
          description: "Creates a new ticket panel for your server.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 3,
          minArgs: 0,
          options: [],
          aliases: [],
          usage: "panels new",
          required: "ticket",
          commandName: "panels new",
        },
        modify: {
          name: "Ticket Panels - Modify",
          description: "Modifies the data of a ticket panel.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 3,
          minArgs: 0,
          options: [],
          aliases: [],
          usage: "panels modify <panel id> [option] [option parameter]",
          required: "ticket",
          commandName: "panels modify",
        },
        delete: {
          name: "Ticket Panels - Delete",
          description: "Deletes a ticket panel.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 3,
          minArgs: 0,
          options: [],
          aliases: [],
          usage: "panels delete <panel id>",
          required: "ticket",
          commandName: "panels delete",
        }
      }
    },
    tsettings: {
      name: "Ticket Settings",
      description: "Allows users to view or modify ticket settings.",
      permissions: ["ADMINISTRATOR"],
      clientPerms: [],
      cooldown: 3,
      minArgs: 0,
      options: [],
      aliases: ["ticketsettings", "tset"],
      usage: "tsettings [setting] [option parameter]",
      required: "ticket",
      commandName: "tsettings"
    }
  },
  moderator: {
    announce: {
      name: "Announce",
      description: "Sends an announcement to a channel.",
      permissions: ["SEND_MESSAGES"],
      clientPerms: ["SEND_MESSAGES"],
      cooldown: 3,
      minArgs: 1,
      options: ["everyone", "here", "role"],
      aliases: ["announcement", "anounce"],
      usage: "announce [option] <channel> <announcement>",
      required: "mod",
      commandName: "announce",
      option: {
        everyone: {
          name: "Announce - Everyone",
          description: "Sends an announcement to a channel that pings @everyone.",
          permissions: ["SEND_MESSAGES", "MENTION_EVERYONE"],
          clientPerms: ["SEND_MESSAGES", "MENTION_EVERYONE"],
          cooldown: 3,
          minArgs: 1,
          options: [],
          aliases: [],
          usage: "announce everyone <channel> <announcement>",
          required: "admin",
          commandName: "announce everyone"
        },
        here: {
          name: "Announce - Here",
          description: "Sends an announcement to a channel that pings @here.",
          permissions: ["SEND_MESSAGES", "MENTION_EVERYONE"],
          clientPerms: ["SEND_MESSAGES", "MENTION_EVERYONE"],
          cooldown: 3,
          minArgs: 1,
          options: [],
          aliases: [],
          usage: "announce here <channel> <announcement>",
          required: "admin",
          commandName: "announce here"
        },
        role: {
          name: "Announce - Role",
          description: "Sends an announcement to a channel that pings a role.",
          permissions: ["SEND_MESSAGES"],
          clientPerms: ["SEND_MESSAGES"],
          cooldown: 3,
          minArgs: 1,
          options: [],
          aliases: [],
          usage: "announce role <role> <channel> <announcement>",
          required: "admin",
          commandName: "announce role"
        }
      }
    },
    ban: {
      name: "Ban",
      description: "Permanently removes members from your server, banned users are not able to rejoin unless unbanned.",
      permissions: ["BAN_MEMBERS"],
      clientPerms: ["BAN_MEMBERS"],
      cooldown: 4,
      minArgs: 1,
      options: ["softban"],
      aliases: [],
      usage: "ban <user> [reason]",
      required: "mod",
      commandName: "ban",
      option: {
        soft: {
          name: "Softban",
          description: "Bans members from your server without deleting previous messages.",
          permissions: ["BAN_MEMBERS"],
          clientPerms: ["BAN_MEMBERS"],
          cooldown: 4,
          minArgs: 1,
          options: [],
          aliases: ["sban"],
          usage: "softban <user> [reason]",
          required: "mod",
          commandName: "softban"
        }
      }
    },
    embed: {
      name: "Embed",
      description: "Creates a customizeable embed to send in any channel.",
      permissions: ["MANAGE_MESSAGES"],
      clientPerms: ["SEND_MESSAGES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["emb"],
      usage: "embed ~<title>~ <description>",
      required: "mod",
      commandName: "embed"
    },
    kick: {
      name: "Kick",
      description: "Removes members from your server, kicked users are able to rejoin.",
      permissions: ["KICK_MEMBERS"],
      clientPerms: ["KICK_MEMBERS"],
      cooldown: 1,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "kick <user> [reason]",
      required: "mod",
      commandName: "kick"
    },
    mute: {
      name: "Mute",
      description: "Removes the ablity for a user to type in a text channel.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 7,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "mute <user> [duration] [reason]",
      required: "mod",
      commandName: "mute"
    },
    nickname: {
      name: "Nickname",
      description: "Modifies the nickname of members in your server.",
      permissions: ["MANAGE_NICKNAMES"],
      clientPerms: ["MANAGE_NICKNAMES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "nickname <user> <new nickname | reset>",
      required: "mod",
      commandName: "nickname"
    },
    purge: {
      name: "Purge",
      description: "Quickly deletes messages from a channel.",
      permissions: ["MANAGE_MESSAGES"],
      clientPerms: ["MANAGE_MESSAGES"],
      cooldown: 3,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "purge <number>",
      required: "mod",
      commandName: "purge"
    },
    slowmode: {
      name: "Slowmode",
      description: "Limits how fast users are able to send messages.",
      permissions: ["MANAGE_CHANNELS"],
      clientPerms: ["MANAGE_CHANNELS"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["slow", "smode"],
      usage: "slowmode [channel] <number | off>",
      required: "mod",
      commandName: "slowmode"
    },
    unban: {
      name: "Un-Ban",
      description: "Removes bans from users.",
      permissions: ["BAN_MEMBERS"],
      clientPerms: ["BAN_MEMBERS"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["un-ban"],
      usage: "unban <user> [reason]",
      required: "mod",
      commandName: "unban"
    },
    unmute: {
      name: "Un-Mute",
      description: "Removes mutes from users.",
      permissions: ["MANAGE_CHANNELS"],
      clientPerms: ["MANAGE_CHANNELS"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["un-mute"],
      usage: "unmute <user> [reason]",
      required: "mod",
      commandName: "unmute"
    },
    warn: {
      name: "Warn",
      description: "Creates a logged warning attached to a certain user.",
      permissions: ["MANAGE_NICKNAMES"],
      clientPerms: [],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "warn <user> [warning]",
      required: "mod",
      commandName: "warn"
    },
    warnings: {
      name: "Warnings",
      description: "Views all warnings from a particular user.",
      permissions: ["MANAGE_NICKNAMES"],
      clientPerms: [],
      cooldown: 3,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "warnings <member>",
      required: "mod",
      commandName: "warnings"
    }
  },
  administrator: {
    addrole: {
      name: "Add Role",
      description: "Adds a specific role to a user.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["giverole"],
      usage: "addrole <user> <role>",
      required: "admin",
      commandName: "addrole",
    },
    addroles: {
      name: "Add Roles",
      description: "Adds multiple roles to a user.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 10,
      minArgs: 1,
      options: [],
      aliases: ["giveroles"],
      usage: "addroles <user> <roles>",
      required: "admin",
      commandName: "addroles",
    },
    create: {
      name: "Create",
      description: "Creates roles and channels in your server.",
      permissions: ["MANAGE_CHANNELS", "MANAGE_ROLES"],
      clientPerms: ["MANAGE_CHANNELS", "MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: ["channel", "role", "voice"],
      aliases: ["crt"],
      usage: "create <option> <name>",
      required: "admin",
      commandName: "create",
      option: {
        channel: {
          name: "Create - Channel",
          description: "Creates text channels in your server.",
          permissions: ["MANAGE_CHANNELS"],
          clientPerms: ["MANAGE_CHANNELS"],
          cooldown: 2,
          options: [],
          aliases: [],
          usage: "create channel <name>",
          required: "admin",
          commandName: "create channel"
        },
        role: {
          name: "Create - Role",
          description: "Creates roles in your server.",
          permissions: ["MANAGE_ROLES"],
          clientPerms: ["MANAGE_ROLES"],
          cooldown: 2,
          options: [],
          aliases: [],
          usage: "create role <name>",
          required: "admin",
          commandName: "create role"
        },
        voice: {
          name: "Create - Voice Channel",
          description: "Creates voice channels in your server.",
          permissions: ["MANAGE_CHANNELS"],
          clientPerms: ["MANAGE_CHANNELS"],
          cooldown: 2,
          options: [],
          aliases: [],
          usage: "create voice <name>",
          required: "admin",
          commandName: "create voice"
        }
      }
    },
    delete: {
      name: "Delete",
      description: "Deletes roles and channels in your server.",
      permissions: ["MANAGE_CHANNELS", "MANAGE_ROLES"],
      clientPerms: ["MANAGE_CHANNELS", "MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "delete <role | channel>",
      required: "admin",
      commandName: "delete",
      option: {
        channel: {
          name: "Delete - Channel",
          description: "Deletes channels in your server.",
          permissions: ["MANAGE_CHANNELS"],
          clientPerms: ["MANAGE_CHANNELS"],
          cooldown: 2,
          options: [],
          aliases: [],
          usage: "delete <channel>",
          required: "admin",
          commandName: "delete channel"
        },
        role: {
          name: "Delete - Role",
          description: "Deletes roles in your server.",
          permissions: ["MANAGE_ROLES"],
          clientPerms: ["MANAGE_ROLES"],
          cooldown: 2,
          options: [],
          aliases: [],
          usage: "delete <role>",
          required: "admin",
          commandName: "delete role"
        }
      }
    },
    hide: {
      name: "Hide",
      description: "Prevents all users from being able to see a certain channel.",
      permissions: ["MANAGE_CHANNELS"],
      clientPerms: ["MANAGE_CHANNELS"],
      cooldown: 3,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "hide [channel] [reason]",
      required: "admin",
      commandName: "hide"
    },
    hoist: {
      name: "Hoist",
      description: "Separates users with a role differently from online members.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "hoist <role>",
      required: "admin",
      commandName: "hoist"
    },
    lock: {
      name: "Lock",
      description: "Prevents all users from being able to type in a text channel.",
      permissions: ["MANAGE_CHANNELS"],
      clientPerms: ["MANAGE_CHANNELS"],
      cooldown: 3,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "lock [channel] [reason]",
      required: "admin",
      commandName: "lock"
    },
    removerole: {
      name: "Remove Role",
      description: "Removes a specific role from a user.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["takerole"],
      usage: "removerole <user> <role>",
      required: "admin",
      commandName: "removerole",
    },
    removeroles: {
      name: "Remove Role",
      description: "Removes multiple roles from a user.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 10,
      minArgs: 1,
      options: [],
      aliases: ["takeroles"],
      usage: "removeroles <user> <roles>",
      required: "admin",
      commandName: "removeroles",
    },
    modify: {
      name: "Modify",
      description: "Allows you to modify role and channel properties.",
      permissions: "MANAGE_ROLES",
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: ["name", "colour", "mention"],
      aliases: [],
      usage: "modify <channel / role> <option> <option parameter>",
      required: "admin",
      commandName: "modify"
    },
    settings: {
      name: "Settings",
      description: "Allows you to view and configure your server settings.",
      permissions: ["ADMINISTRATOR"],
      clientPerms: [],
      cooldown: 1,
      minArgs: 0,
      options: ["prefix", "adminrole", "modrole", "logchannel", "welcome", "welcomechannel", "welcomerole"],
      aliases: ["setting", "set"],
      usage: "settings [option] [option parameter]",
      required: "admin",
      commandName: "settings",
      option: {
        prefix: {
          name: "Setting - Prefix",
          description: "Modifies the current prefix for your server.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings pre"],
          usage: "settings prefix <new prefix>",
          required: "admin",
          commandName: "settings prefix"
        },
        adminrole: {
          name: "Setting - Administrator Role",
          description: "Changes what roles will have access to administrator commands.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings admin", "settings administratorrole"],
          usage: "settings adminrole <role>",
          required: "admin",
          commandName: "settings adminrole"
        },
        modrole: {
          name: "Setting - Moderator Role",
          description: "Changes what roles will have access to moderator commands.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings mod", "settings moderatorrole"],
          usage: "settings modrole <role>",
          required: "admin",
          commandName: "settings modrole"
        },
        logchannel: {
          name: "Setting - Log Channel",
          description: "Changes what channel server logs are sent to.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings log", "settings logchan"],
          usage: "settings logchannel <channel>",
          required: "admin",
          commandName: "settings logchannel"
        },
        mutedrole: {
          name: "Setting - Muted Role",
          description: "Changes what role will be granted to users who are muted.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings muted"],
          usage: "settings mutedrole <role>",
          required: "admin",
          commandName: "settings mutedrole"
        },
        welcome: {
          name: "Setting - Welcome System",
          description: "Enables or disable the welcoming system.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings welc", "settings welcomesystem"],
          usage: "settings welcome <on | off>",
          required: "admin",
          commandName: "settings welcome"
        },
        welcomechannel: {
          name: "Setting - Welcome Channel",
          description: "Changes what channel new users are welcomed in.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings welcomechan", "settings welcchan"],
          usage: "settings welcomechannel <channel>",
          required: "admin",
          commandName: "settings welcomechannel"
        },
        welcomerole: {
          name: "Setting - Welcome Role",
          description: "Changes what role new users recieve once they join your server.",
          permissions: ["ADMINISTRATOR"],
          clientPerms: [],
          cooldown: 1,
          aliases: ["settings welcomerole"],
          usage: "settings welcomerole <role>",
          required: "admin",
          commandName: "settings welcomerole"
        },
      }
    },
    unhoist: {
      name: "Un-Hoist",
      description: "Turns off the hoist for a role.",
      permissions: ["MANAGE_ROLES"],
      clientPerms: ["MANAGE_ROLES"],
      cooldown: 2,
      minArgs: 1,
      options: [],
      aliases: ["un-hoist"],
      usage: "unhoist <role>",
      required: "admin",
      commandName: "unhoist"
    },
    unhide: {
      name: "Un-Hide",
      description: "Allows users to be able to see a certain channel again.",
      permissions: ["MANAGE_CHANNELS"],
      clientPerms: ["MANAGE_CHANNELS"],
      cooldown: 3,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "unhide [channel] [reason]",
      required: "admin",
      commandName: "unhide"
    },
    unlock: {
      name: "Un-Lock",
      description: "Re-enables the ability for users to talk in a text channel.",
      permissions: ["MANAGE_CHANNELS"],
      clientPerms: ["MANAGE_CHANNELS"],
      cooldown: 5,
      minArgs: 0,
      options: [],
      aliases: ["un-lock"],
      usage: "unlock [channel] [reason]",
      required: "admin",
      commandName: "unlock"
    }
  },
  support: {
    error: {
      name: "Error",
      description: "Retrieves error information from an error ID.",
      permissions: ["SUPPORT_TEAM"],
      clientPerms: [],
      cooldown: 3,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "error <id>",
      required: "support",
      commandName: "error"
    },
    shelp: {
      name: "Support Help",
      description: "Provides information about support team commands.",
      permissions: ["SUPPORT_TEAM"],
      clientPerms: [],
      cooldown: 2,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "shelp [command]",
      required: "support",
      commandName: "shelp"
    }
  },
  developer: {
    blacklist: {
      name: "Blacklist",
      description: "Disallows certain users from using commands.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 1,
      options: [],
      aliases: [],
      usage: "blacklist <user> [reason]",
      required: "dev",
      commandName: "blacklist",
    },
    devlock: {
      name: "Developer Lock",
      description: "Disables commands when they contain bugs, are under development, or contain security risks.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 1,
      options: ["view"],
      aliases: ["dlock", "dl", "developerlock"],
      usage: "devlock <command> [guild] [option | reason]",
      required: "dev",
      commandName: "devlock",
      option: {
        view: {
          name: "Developer Lock - View",
          description: "Used to view the currently locked commands.",
          permissions: ["BOT_DEVELOPER"],
          clientPerms: [],
          cooldown: 0,
          minArgs: 1,
          options: [],
          aliases: ["check"],
          usage: "devlock view",
          required: "dev",
          commandName: "devlock view",
        }
      }
    },
    devhelp: {
      name: "Developer Help",
      description: "Shows a list of developer commands.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 0,
      options: [],
      aliases: ["dhelp"],
      usage: "devmode [option]",
      required: "dev",
      commandName: "devhelp"
    },
    devmode: {
      name: "Developer Mode",
      description: "Enables the bot developer mode.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 1,
      options: [],
      aliases: ["dmode", "devm"],
      usage: "devmode <on | off>",
      required: "dev",
      commandName: "devmode"
    },
    eval: {
      name: "Eval",
      description: "Executes javascript code directly from discord.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 1,
      options: ["silent"],
      aliases: ["e"],
      usage: "eval [option] <code>",
      required: "dev",
      commandName: "eval",
      option: {
        silent: {
          name: "Eval - Silent",
          description: "Executes javascript code silently.",
          permissions: ["BOT_DEVELOPER"],
          clientPerms: [],
          cooldown: 0,
          minArgs: 1,
          options: [],
          aliases: ["s"],
          usage: "eval silent <code>",
          required: "dev",
          commandName: "eval silent",
        },
        async: {
          name: "Eval - Async",
          description: "Executes javascript code in an asynchronous thread.",
          permissions: ["BOT_DEVELOPER"],
          clientPerms: [],
          cooldown: 0,
          minArgs: 1,
          options: [],
          aliases: ["a"],
          usage: "eval async <code>",
          required: "dev",
          commandName: "eval async",
        }
      }
    },
    logs: {
      name: "Logs",
      description: "Allows the bot developer to view and create logs.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 0,
      options: ["add", "remove", "persistent"],
      aliases: [],
      usage: "logs <option>",
      required: "dev",
      commandName: "logs"
    },
    reload: {
      name: "Reload",
      description: "Reloads the content of a command file.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 1,
      options: [],
      aliases: ["rld"],
      usage: "reload <command name>",
      required: "dev",
      commandName: "reload"
    },
    reset: {
      name: "Reset",
      description: "Resets database keys.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 1,
      options: ["cooldown", "settings"],
      aliases: ["rst"],
      usage: "reset <option> <option parameter>",
      required: "dev",
      commandName: "reset",
      option: {
        cooldown: {
          name: "Reset - Cooldown",
          description: "Resets the command cooldown for a specific user.",
          permissions: ["BOT_DEVELOPER"],
          clientPerms: [],
          cooldown: 0,
          minArgs: 1,
          options: [],
          aliases: [],
          usage: "reset cooldown <user> [command]",
          required: "dev",
          commandName: "reset cooldown",
        },
        settings: {
          name: "Reset - Settings",
          description: "Resets the settings for a particular guild.",
          permissions: ["BOT_DEVELOPER"],
          clientPerms: [],
          cooldown: 0,
          minArgs: 1,
          options: [],
          aliases: [],
          usage: "reset settings <guild> [setting]",
          required: "dev",
          commandName: "reset settings",
        }
      }
    },
    restart: {
      name: "Restart",
      description: "Restarts Logic Link.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 0,
      options: [],
      aliases: ["rstart", "rst"],
      usage: "restart",
      required: "dev",
      commandName: "restart"
    },
    shutdown: {
      name: "Shutdown",
      description: "Logs out of Logic Link.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "shutdown",
      required: "dev",
      commandName: "shutdown"
    },
    test: {
      name: "Test",
      description: "A command used to test out new features.",
      permissions: ["BOT_DEVELOPER"],
      clientPerms: [],
      cooldown: 0,
      minArgs: 0,
      options: [],
      aliases: [],
      usage: "test",
      required: "dev",
      commandName: "test"
    },
  },
  total: {
    general: ["avatar", "botinfo", "help", "info", "invite", "membercount", "pastebin", "ping", "ticket", "uptime", "voice", "whois"],
    ticket: {
      basic: ["thelp"],
      support: [],
      admin: ["panels", "tsettings"]
    },
    moderator: ["announce", "ban", "embed", "kick", "mute", "nickname", "purge", "slowmode", "unban", "unmute", "warn", "warnings"],
    administrator: ["addrole", "create", "delete", "hide", "hoist", "lock", "modify", "removerole", "settings", "unhide", "unhoist", "unlock"],
    support: ["error", "shelp"],
    developer: ["devhelp", "devlock", "devmode", "eval", "logs", "reload", "reset", "restart", "shutdown", "test"]
  },
  all: ["admin", "avatar", "ban", "botinfo", "create", "delete", "devlock", "eval", "help", "invite", "kick", "membercount", "mute", "nickname", "ping", "purge", "reload", "restart", "roles", "settings", "shutdown", "slowmode", "test", "ticket", "unban", "unmute", "uptime", "voice"],
  settingsOptions: ["prefix", "modrole", "adminrole", "logchannel", "mutedrole", "welcome", "welcomerole", "welcomechannel"],
  settingsOptionsAliases: ["pre", "mod", "moderatorrole", "admin", "administratorrole", "log", "logchan", "muted", "welc","welcomesystem", "welcrole", "welcchan", "welcomechan"],
  aliases: {
    "av": "avatar",
    "binfo": "botinfo",
    "inv": "invite",
    "mcount": "membercount",
    "memcount": "membercount",
    "mc": "membercount",
    "vc": "voice",
    "un-mute": "unmute",
    "un-ban": "unban",
    "role": "roles",
    "setting": "settings",
    "set": "settings",
    "e": "eval",
    "rld": "reload",
    "crt": "create",
    "tickets": "ticket",
    "tck": "ticket",
    "slow": "slowmode",
    "smode": "slowmode",
    "slowmod": "slowmode",
    "setnick": "nickname",
    "nickset": "nickname",
    "nick": "nickname",
    "dlock": "devlock",
    "developerlock": "devlock",
    "dl": "devlock",
    "un-lock": "unlock",
    "up-time": "uptime",
    "un-hoist": "unhoist",
    "giverole": "addrole",
    "takerole": "removerole",
    "paste": "pastebin",
    "giveroles": "addroles",
    "takeroles": "removeroles",
    "upt": "uptime",
    "commands": "help",
    "cmds": "help",
    "cmd": "help",
    "warning": "warnings",
    "warns": "warnings",
    "dhelp": "devhelp",
    "emb": "embed",
    "log": "logs",
    "serverinfo": "info",
    "channelinfo": "info",
    "roleinfo": "info",
    "sinfo": "info",
    "cinfo": "info",
    "rinfo": "info",
    "softban": "ban",
    "sban": "ban",
    "tickethelp": "thelp",
    "ticketsettings": "tsettings",
    "ticketsetting": "tsettings",
    "tset": "tsettings",
    "ticketpanels": "panels",
    "tpanel": "panels",
    "tpanels": "panels",
    "ticketpanel": "panels",
    "panel": "panels",
    "errors": "error"
  }
}